### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by jhannah** [ryanhodson/aintcms#1]
Any tips? Contact NPM? Thanks.

```
➜  jhannah-iMac:aintcms git:(master) npm install
npm http GET https://registry.npmjs.org/github
npm http GET https://registry.npmjs.org/del
npm http GET https://registry.npmjs.org/gulp
npm http GET https://registry.npmjs.org/electron-prebuilt
npm http GET https://registry.npmjs.org/jquery
npm http GET https://registry.npmjs.org/swig
npm http GET https://registry.npmjs.org/gulp-swig
npm http GET https://registry.npmjs.org/async
npm http 200 https://registry.npmjs.org/jquery
npm http 200 https://registry.npmjs.org/del
npm http GET https://registry.npmjs.org/jquery/-/jquery-2.2.3.tgz
npm http GET https://registry.npmjs.org/del/-/del-2.2.0.tgz
npm http 200 https://registry.npmjs.org/github
npm http GET https://registry.npmjs.org/github/-/github-0.2.4.tgz
npm http 200 https://registry.npmjs.org/gulp
npm http GET https://registry.npmjs.org/gulp/-/gulp-3.9.1.tgz
npm http 200 https://registry.npmjs.org/gulp-swig
npm http GET https://registry.npmjs.org/gulp-swig/-/gulp-swig-0.8.0.tgz
npm http 200 https://registry.npmjs.org/swig
npm http GET https://registry.npmjs.org/swig/-/swig-1.4.2.tgz
npm http 200 https://registry.npmjs.org/electron-prebuilt
npm ERR! registry error parsing json
npm ERR! SyntaxError: Unexpected token
npm ERR! ��Ko�F��
npm ERR! �S���OA�Csȭ��h�}
... lots more garbage here, then ...
npm ERR!     at Object.parse (native)
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:238:23)
npm ERR!     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/index.js:876:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/index.js:827:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:910:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 15.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/jhannah/src/aintcms
npm ERR! node -v v0.10.13
npm ERR! npm -v 1.3.2
npm ERR! type unexpected_token
npm http 200 https://registry.npmjs.org/jquery/-/jquery-2.2.3.tgz
npm http 200 https://registry.npmjs.org/async
npm http 200 https://registry.npmjs.org/del/-/del-2.2.0.tgz
npm http 200 https://registry.npmjs.org/github/-/github-0.2.4.tgz
npm http 200 https://registry.npmjs.org/gulp/-/gulp-3.9.1.tgz
npm http GET https://registry.npmjs.org/async/-/async-2.0.0-rc.2.tgz
npm http 200 https://registry.npmjs.org/swig/-/swig-1.4.2.tgz
npm http 200 https://registry.npmjs.org/async/-/async-2.0.0-rc.2.tgz
npm http 200 https://registry.npmjs.org/gulp-swig/-/gulp-swig-0.8.0.tgz
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/jhannah/src/aintcms/npm-debug.log
npm ERR! not ok code 0
```

**Comment by ryanhodson** [comment]
Damn that was fast. Thanks for the interest :)

I'll take a look later tonight. Electron is a little weird to set up, so
I'm not surprised there's some strange dependency things going on.

Cheers,
Ry

**Comment by petetnt** [comment]
This was due to https://github.com/npm/npm/issues/12196 which is now fixed :)
